language: python
python:
  - "3.5"
before_install:
  - eval "$(curl -sL https://raw.githubusercontent.com/travis-ci/gimme/master/gimme | GIMME_GO_VERSION=1.6 bash)"
  - mkdir gocode
  - export GOPATH=$(pwd)/gocode
  - export PATH=$GOPATH/bin:$PATH
  - nvm install node
  - npm install -g elm
install:
  - go get github.com/constabulary/gb/...
  - pip install -r requirements_dev.txt coveralls
script: py.test -sv
after_success: coveralls
